---
# Config environment

  - name: "Create download directory"
    file: 
      path: $HOME/Downloads
      state: directory
      group: "{{ ansible_user }}"
      owner: "{{ ansible_user }}"
      mode: '0755'
  
  - name: "Create download directory"
    file: 
      path: $HOME/Downloads
      state: directory
      group: "{{ confluence_user }}"
      owner: "{{ confluence_user }}"
      mode: '0755'
    become: true
    become_user: "{{confluence_user}}"

  - name: "Create confluence installation directory" 
    file:
      path: /opt/confluence
      state: directory
      group: "{{ confluence_user }}"
      owner: "{{ confluence_user }}"
      mode: '0755'
    become: true
    become_user: "{{main_admin}}"
  
  - name: "Download Confluence"
    get_url:
      url: https://www.atlassian.com/software/confluence/downloads/binary/atlassian-confluence-7.1.0.tar.gz
      dest: $HOME/Downloads
      group: "{{ confluence_user }}"
      owner: "{{ confluence_user }}"
      mode: '0644'
    become: true
    become_user: "{{confluence_user}}"
  
  - name: "Download Java-Mysql connector 5.1.42"
    get_url: 
      url: https://downloads.mysql.com/archives/get/p/3/file/mysql-connector-java-5.1.42.tar.gz
      dest: $HOME/Downloads
      group: "{{ confluence_user }}"
      owner: "{{ confluence_user }}"
      mode: '0644'
    become: true
    become_user: "{{confluence_user}}"

  - name: "Unarchive confluence to installation folder"
    unarchive:
      src: /home/{{ansible_user}}/Downloads/atlassian-confluence-7.1.0.tar.gz
      dest: /opt/confluence
      remote_src: yes
      group: "{{confluence_user}}"
      owner: "{{confluence_user}}"
      creates: /opt/confluence/atlassian-confluence-7.1.0
    become: true
    become_user: "{{main_admin}}"
  
  - stat:
      path: /opt/confluence/NOTICE
    register: conf_dir

  - name: Rename atlassian-confluence directory
    shell: mv /opt/confluence/atlassian-confluence*/* /opt/confluence
    when: conf_dir.stat.exists == false
    become: true
    become_user: "{{main_admin}}"

  - name: "Create confluence home directory"
    file:
      path: /opt/confluence-home
      state: directory
      group: "{{ confluence_user }}"
      owner: "{{ confluence_user }}"
      mode: '0755'
    become: true
    become_user: "{{main_admin}}"

  - name: "Unarchive java mysql connector"
    unarchive:
      src: /home/{{confluence_user}}/Downloads/mysql-connector-java-5.1.42.tar.gz
      dest: /opt/confluence/confluence/WEB-INF/lib
      remote_src: yes
      group: "{{confluence_user}}"
      owner: "{{confluence_user}}"
    become: true
    become_user: "{{main_admin}}"
  
  - name: "Download mysql repo"
    get_url:
      url:  http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
      dest: $HOME/Downloads
      group: "{{ confluence_user }}"
      owner: "{{ confluence_user }}"
      mode: '0644'
    become: true
    become_user: "{{ confluence_user }}"

  - name: "Install Java jdk8"
    yum: pkg=java-1.8.0-openjdk state=installed
    become: true
    become_user: "{{main_admin}}"

  - name: "Install more packages"
    yum: pkg={{ item }} state=installed
    with_items:
      - nmap
      - httpd
      - git
      - tree
      - lynx
      - elinks
      - vsftpd
      - bind
    become: true
    become_user: "{{main_admin}}"

  - name: "Add mysql community to repo"
    yum:
      name: /home/{{confluence_user}}/Downloads/mysql-community-release-el7-5.noarch.rpm
      state: present
    become: true
    become_user: "{{main_admin}}"

  - stat:
      path: /opt/confluence/atlassian-confluence-7.1.0/NOTICE
    register: conf_install_dir

  - name: "Clean temporary installation files and folder"
    shell: rm -rf /opt/confluence/atlassian-confluence-7.1.0
    when: conf_install_dir.stat.exists == true
    become: true
    become_user: "{{main_admin}}"

  - stat:
      path: $HOME/Downloads/atlassian-confluence-7.1.0.tar.gz
    register: conf_tar_dir

  - name: "Clean temporary installation files and folder"
    shell: rm -rf $HOME/Downloads/atlassian-confluence-7.1.0.tar.gz
    when: conf_tar_dir.stat.exists == true
    become: true
    become_user: "{{main_admin}}"
  
  - stat:
      path: $HOME/Downloads/mysql-connector-java-5.1.42.tar.gz
    register: mysql_tar_dir

  - name: "Clean temporary installation files and folder"
    shell: rm -rf $HOME/Downloads/mysql-connector-java-5.1.42.tar.gz
    when: mysql_tar_dir.stat.exists == true
    become: true
    become_user: "{{main_admin}}"
  
  - name: "Install mysql package"
    yum: pkg=mysql-server state=installed
    become: true
    become_user: "{{main_admin}}"

  - name: "Start and enable mysql service"
    systemd: name=mysql state=restarted enabled=yes
    become: true
    become_user: "{{main_admin}}"

